services:
  api:
    image: nginx:alpine
    ports:
      - "8000:80"
    volumes:
      - ./src/api:/var/www/html
      - ./docker/conf/api.conf:/etc/nginx/conf.d/api.conf
      - ./docker/log:/var/log/nginx
    depends_on:
      - phpapi

  client:
    image: nginx:alpine
    ports:
      - "8001:80"
    volumes:
      - ./src/client:/var/www/html
      - ./docker/conf/client.conf:/etc/nginx/conf.d/client.conf
      - ./docker/log:/var/log/nginx
    depends_on:
      - phpclient

  phpapi:
    image: ghcr.io/icemaltacode/sc-bed-php:latest
    volumes:
      - ./src/api:/var/www/html
    depends_on:
      mariadb:
        condition: service_healthy

  phpclient:
    image: ghcr.io/icemaltacode/sc-bed-php:latest
    volumes:
      - ./src/client:/var/www/html
    depends_on:
      mariadb:
        condition: service_healthy

  mariadb:
    image: mariadb:latest
    ports:
      - "3306:3306"
    environment:
      MARIADB_ROOT_PASSWORD: root
    healthcheck:
      test: ["CMD", "mariadb-admin" , "-u", "root", "-proot", "ping", "-h", "localhost"]
      start_period: 10s
      interval: 5s
      timeout: 3s
      retries: 3
    volumes:
      - ./support/db.sql:/docker-entrypoint-initdb.d/db.sql
      - db_data:/var/lib/mysql

  print-status:
    image: busybox
    command: "echo '---\nAPI: http://localhost:8000. CLIENT: http://localhost:8001. USE CTRL+C TO TERMINATE.\n---'"
    depends_on:
      api:
        condition: service_started
      client:
        condition: service_started
      mariadb:
        condition: service_healthy

volumes:
  db_data: